// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oyasumi.Database;

namespace oyasumi.Migrations
{
    [DbContext(typeof(OyasumiDbContext))]
    [Migration("20201017214009_Beatmaps")]
    partial class Beatmaps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("oyasumi.Database.Models.DbBeatmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("ApproachRate")
                        .HasColumnType("float");

                    b.Property<string>("Artist")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<float>("BPM")
                        .HasColumnType("float");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("int");

                    b.Property<string>("BeatmapMd5")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("BeatmapSetId")
                        .HasColumnType("int");

                    b.Property<float>("CircleSize")
                        .HasColumnType("float");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DifficultyName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Frozen")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("HPDrainRate")
                        .HasColumnType("float");

                    b.Property<float>("OverallDifficulty")
                        .HasColumnType("float");

                    b.Property<int>("PassCount")
                        .HasColumnType("int");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<float>("Stars")
                        .HasColumnType("float");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Beatmaps");
                });

            modelBuilder.Entity("oyasumi.Database.Models.UserStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("AccuracyCtb")
                        .HasColumnType("float");

                    b.Property<float>("AccuracyMania")
                        .HasColumnType("float");

                    b.Property<float>("AccuracyOsu")
                        .HasColumnType("float");

                    b.Property<float>("AccuracyTaiko")
                        .HasColumnType("float");

                    b.Property<int>("PerformanceCtb")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceMania")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceOsu")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceTaiko")
                        .HasColumnType("int");

                    b.Property<int>("PlaycountCtb")
                        .HasColumnType("int");

                    b.Property<int>("PlaycountMania")
                        .HasColumnType("int");

                    b.Property<int>("PlaycountOsu")
                        .HasColumnType("int");

                    b.Property<int>("PlaycountTaiko")
                        .HasColumnType("int");

                    b.Property<long>("RankedScoreCtb")
                        .HasColumnType("bigint");

                    b.Property<long>("RankedScoreMania")
                        .HasColumnType("bigint");

                    b.Property<long>("RankedScoreOsu")
                        .HasColumnType("bigint");

                    b.Property<long>("RankedScoreTaiko")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalScoreCtb")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalScoreMania")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalScoreOsu")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalScoreTaiko")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("oyasumi.Database.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UsernameAka")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UsernameSafe")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
